### ISSUE TITLE
`git ignore completion bash` panics

### ISSUE THREAD

**Issue by knutwalker** [sondr3/git-ignore#28]
I tried to run `git ignore completion bash` and got a panic:

```sh
$ RUST_BACKTRACE=full git ignore completion bash
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/knut/.cargo/registry/src/github.com-1ecc6299db9ec823/clap_complete-4.0.2/src/generator/utils.rs:26:
15
stack backtrace:
   0:        0x10256def4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h340d2c2f5451c7ef
   1:        0x1024bea30 - core::fmt::write::h2863e241f47a1341
   2:        0x10254d388 - std::io::Write::write_fmt::ha5318cf93d5caf66
   3:        0x10256ebd8 - std::panicking::default_hook::{{closure}}::h31f49defe78b2502
   4:        0x10256f34c - std::panicking::rust_panic_with_hook::h4de5a69993dd3bcc
   5:        0x10256eeb4 - std::panicking::begin_panic_handler::{{closure}}::h4e553c52739d27ac
   6:        0x10256ee48 - std::sys_common::backtrace::__rust_end_short_backtrace::h7bcd4de6784f51ff
   7:        0x10256ee24 - _rust_begin_unwind
   8:        0x10259bce8 - core::panicking::panic_fmt::h72cfce715a1683d6
   9:        0x10259bd88 - core::panicking::panic::h86f8e106956f9d6c
  10:        0x1024ab7cc - clap_complete::generator::utils::find_subcommand_with_path::h3101cf8b5d682f98
  11:        0x1024b7d54 - clap_complete::shells::bash::all_options_for_path::he6b2866129a89149
  12:        0x1024ae590 - <clap_complete::shells::shell::Shell as clap_complete::generator::Generator>::generate::h2304bcf3cd790fe2
  13:        0x1024f6e74 - git_ignore::main::h126a1e251f52f88b
  14:        0x1024d922c - std::sys_common::backtrace::__rust_begin_short_backtrace::h61a9f3523f11fa1f
  15:        0x1024f5554 - _main
```

From looking at what `clap_complete` does:

It tries to find a command based on the `bin_name`:

https://github.com/clap-rs/clap/blob/clap_complete-v4.0.3/clap_complete/src/shells/bash.rs#L17-L19

then

https://github.com/clap-rs/clap/blob/clap_complete-v4.0.3/clap_complete/src/shells/bash.rs#L65

then

https://github.com/clap-rs/clap/blob/clap_complete-v4.0.3/clap_complete/src/shells/bash.rs#L217-L220

then

https://github.com/clap-rs/clap/blob/clap_complete-v4.0.3/clap_complete/src/generator/utils.rs#L25-L27

Maybe it fails because the name is set to [`git ignore`](https://github.com/sondr3/git-ignore/blob/v1.2.1/src/cli.rs#L6) and not `git_ignore`?

I'm running the latest version

```sh
$ git ignore --version
git ignore 1.2.1
```

Generating completions for zsh and fish work fine.

**Comment by sondr3** [comment]
Ack, that's weird. I generate the completions at build time as well and it doesn't fail there, I get a well-formed bash completion file in `./target/assets`. Strange that it doesn't work in the binary itself, I'm using the exact same mechanism for it. Thanks for the report, I'll investigate.

**Comment by sondr3** [comment]
Thanks for the report, turns out you were right! I hardcoded the name in `build.rs` to be `git-ignore`, and see from other completions in git that they also used a dash between the command names. I've fixed it and will push a new version soon.

**Comment by knutwalker** [comment]
Thanks for the quick fix, works like a charm 👍
