### ISSUE TITLE
Add a flag to automatically create `.gitignore`

### ISSUE THREAD

**Issue by giggio** [sondr3/git-ignore#39]
It would be nice if we could do `git ignore -a --save` to just save .gitignore in the `cwd`.

**Comment by sondr3** [comment]
Sounds like a fairly useful addition, thanks. How would this interact with an existing `.gitignore`? Maybe I could add a warning with a `Append to file? [Y/n]` action if it already exists.

**Comment by giggio** [comment]
A warning if a file already exists would be important, but if none exists, then the tool should just write the file.
You could add a `--force` to write without the warning, too, to be used only with `--save`.

**Comment by sondr3** [comment]
I've added this feature to the main branch, you can try it using `cargo install -f --locked --git https://github.com/sondr3/git-ignore` (if you installed via `cargo`). It adds a `--write` flag that creates and writes to `$CWD/.gitignore` if it doesn't exist or warns that you need `--force` to append to it if it exists. Let me know what you think if you get to try it out.

**Comment by sondr3** [comment]
I completely forgot about this, I wanted to let it simmer for a bit in case issues or more features came up but instead forgot to release it. I just pushed the new version to Crates/GitHub, so hopefully `nixpkgs` will update fairly soon!
