### ISSUE TITLE
File conflicts

### ISSUE THREAD

**Issue by GFdevelop** [sondr3/git-ignore#4]
On archlinux I have conflict with git-extras:
```
git-ignore-bin: /usr/bin/git-ignore exists in filesystem (owned by git-extras)
git-ignore-bin: /usr/share/man/man1/git-ignore.1.gz exists in filesystem (owned by git-extras)
```

**Comment by sondr3** [comment]
There's sadly not much that can be done with this, you can download the binary from the releases here on GitHub, rename it and add it to your `$PATH` (and ignore installing the man pages).
