### ISSUE TITLE
 Error("expected value", line: 1, column: 1)

### ISSUE THREAD

**Issue by Windforce17** [sondr3/git-ignore#5]
```
root@na:~#  git ignore --list
Info: You are using cached results, pass '-u' to update the cache

Error: Error("expected value", line: 1, column: 1)
```

**Comment by sondr3** [comment]
I can't reproduce this, it's working locally for me. What version of `git ignore` are you using and is this a recurring problem? The only reason I can imagine getting that error is when fetching from gitignore.io fails or that it can't create the cache file.

**Comment by Windforce17** [comment]
You are right. I use proxy to update and solve problem.but when faild to create cache file,it print a  successful and a error msg meanwhile.
```sh
root@na:~# git-ignore -u
Info: Update successful
Error: Error("expected value", line: 1, column: 1)
```
