### ISSUE TITLE
Auto detect templates based on existing files

### ISSUE THREAD

**Issue by sestrella** [sondr3/git-ignore#7]
I'm pretty new to Rust, but I found this project very interesting and I'll love to submit a PR if the following idea gets approved. I'm wondering if it would make sense to add a flag to infer the `templates` based on files in the current directory, for instance, given a folder with the following files:

```
- Cargo.toml
- package.json
```

The following command:

```
git ignore --auto
```

Should produce the same output as:

```
git ignore node rust
```

There is a long variety of programming languages, but maybe this feature could be initially implemented for some mainstream languages with well-known configuration files.

This flag should work along with the `templates` arguments, so the following command:

```
git ignore --auto linux
```

Should produce the same output as:

```
git ignore node rust linux
```

About use cases, I think this feature would be useful for existing projects that lack a good gitignore file.

**Comment by sondr3** [comment]
This is a really great idea, and one that I'm almost ashamed I haven't though of myself. I would love to see this feature, so feel free to implement it, and ask away if you have any questions :smile:

**Comment by sestrella** [comment]
Great! I'm planning to work on this next week, I'll keep you posted.

**Comment by sestrella** [comment]
@sondr3 I noticed you pushed some improvements (look great), I'm still willing to work on this issue this week, but I noticed it was closed, I reviewed the PR linked to this issue (as well as the other changes in master) but just found some changes to the CI configuration.

**Comment by sondr3** [comment]
Ah, crap, sorry, I thought I created an issue for updating the CI pipeline before the weekend and didn't read closely when I created my commit. :sweat:  I still would love this feature, I'm just working on some long overdue features of my own (namely aliases and having your own templates). I saw that you did some work on the feature this weekend, please continue on it :smiley:

**Comment by sestrella** [comment]
No worries. Actually, I managed to make some progress over the weekend, here is a draft [PR]( https://github.com/sondr3/git-ignore/pull/8). I'm planning to continue working on it this week
